services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c 'python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db



  db:
    image: postgres:14.6-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme


  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: sh -c 'redis-server'
    ports:
      - '6379:6379'


  celery:
    build: .
    container_name: 'app_celery'
    command: sh -c 'celery -A app worker -l info'
    volumes:
      - .:/code
    depends_on:
      - app
      - redis

volumes:
  dev-db-data: