# Generated by Django 4.2.21 on 2025-05-19 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('participants', models.ManyToManyField(null=True, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
