# Generated by Django 4.2.21 on 2025-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_time_alter_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
