# Generated by Django 4.2.21 on 2025-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meeting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
