# Generated by Django 4.2.21 on 2025-05-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
    ]
